version: '3.8'

services:
  app:
    build: .
    container_name: fastapi_app
    command: >

    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${PG_LINK}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      - POSTGRES_URL=${PG_LINK}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: